# run `XXiaoA all_colorschemes` to see all colorschemes
color_scheme: rose-pine

lualine_theme: auto

# Only load the configuration if user's nvim version is expectable if it's true
strict_version: true