# run `:lua vim.pretty_print(vim.tbl_keys(require("core.colorscheme").all_colorschemes))` to see all colorschemes
color_scheme: duskfox

lualine_theme: auto

# Only load the configuration if user's nvim version is expectable if it's true
strict_version: true
