# random gruvbox-material nightfox catppuccin duskfox
color_scheme: gruvbox-material
lualine_theme: auto

# Only load the configuration if user's nvim version is expectable if it's true
strict_version: true
